
const Products = [
  {
    id: 1,
    name: "Wooden Chair",
    price: 2499,
    inStock: true,
    brand: "Sheesham",
  },
  {
    id: 2,
    name: "Dining Table",
    price: 16500,
    inStock: false,
    brand: "Pepperfry",
  },
  {
    id: 3,
    name: "Sofa Set",
    price: 12000,
    inStock: true,
    brand: "Velvet",
  },
  {
    id: 4,
    name: "Double Bed",
    price: 18000,
    inStock: true,
    brand: "Sleepwell",
  },
  {
    id: 5,
    name: "Office Desk",
    price: 9000,
    inStock: true,
    brand: "Shadow Circuit",
  },
  {
    id: 6,
    name: "Wardrobe",
    price: 15000,
    inStock: true,
    brand: "Velvet Voltage",
  },
  {
    id: 7,
    name: "Living Room Set",
    price: 22000,
    inStock: true,
    brand: "Velvet Voltage",
  },
  {
    id: 8,
    name: "Bedroom Wallpaper",
    price: 8000,
    inStock: true,
    brand: "Rock Band Logos",
  },
  {
    id: 9,
    name: "Office Chair",
    price: 3000,
    inStock: true,
    brand: "Catchy",
  },
  {
    id: 10,
    name: "Bookshelf",
    price: 5000,
    inStock: true,
    brand: "Hoobastank",
  },
  {
    id: 11,
    name: "TV Stand",
    price: 4000,
    inStock: true,
    brand: "Elegant",
  },
  {
    id: 12,
    name: "Recliner Sofa",
    price: 19500,
    inStock: true,
    brand: "Franklin",
  },
  {
    id: 13,
    name: "Coffee Table",
    price: 3000,
    inStock: true,
    brand: "Italian",
  },
  {
    id: 14,
    name: "King Size Bed",
    price: 3000,
    inStock: true,
    brand: "Duroflex",
  },
  {
    id: 15,
    name: "Wall Art Frame",
    price: 3000,
    inStock: true,
    brand: "Mural",
  },
];

export default Products;
