import React, { useState } from "react";
import { LucideFileSpreadsheet } from "lucide-react";
// src/Component/API/productData.js
const productData = [
  {
    id: 1,
    name: "Wooden Chair",
    image: "https://www.nadhukan.co.in/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-28-at-10.46.30_a94b5932.jpg",
    price: 4999,
    oldPrice: 6000,
    inStock: true,
    brand: "Sheesham",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Comfortable wooden chair made from premium Sheesham wood, perfect for living or dining spaces."
  },
  {
    id: 2,
    name: "Dining Table",
    image: "https://images.squarespace-cdn.com/content/v1/58b9e3da9de4bbb44f9988ca/272903ed-3d7a-49ae-8432-bb7d21219612/Cascade+House+-+Dining+Room.jpg",
    price: 17500,
    oldPrice: 19999,
    inStock: true,
    brand: "Pepperfry",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Elegant 6-seater dining table with a polished wooden surface and modern design."
  },
  {
    id: 3,
    name: "Sofa Set",
    image: "https://alder.in/wp-content/uploads/2024/05/Waves-311.jpg",
    price: 13999,
    oldPrice: 15999,
    inStock: true,
    brand: "Velvet",
    topProduct: false,
    likedProduct: true,
    quantity:0,
    category: "Furniture",
    description: "Luxurious velvet sofa set with a sleek finish and supreme comfort."
  },
  {
    id: 4,
    name: "Double Bed",
    image: "https://www.nilkamalfurniture.com/cdn/shop/files/MARTHURDBWOSTRWNT-1.webp?v=1753176677",
    price: 18000,
    oldPrice: 19999,
    inStock: true,
    brand: "Sleepwell",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Spacious double bed with modern aesthetics and matching side tables."
  },
  {
    id: 5,
    name: "Office Desk",
    image: "https://wallpapers.com/images/hd/office-desk-with-coastline-view-7pn380tydey5ggor.jpg",
    price: 9000,
    oldPrice: 10999,
    inStock: true,
    brand: "Shadow Circuit",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Modern office desk with clean lines and ample storage space."
  },
  {
    id: 6,
    name: "Wardrobe",
    image: "https://www.caoscreativo.it/wp-content/uploads/2022/12/Carta-da-parati-design-per-armadi-1024x696.jpg",
    price: 15000,
    oldPrice: 16999,
    inStock: true,
    brand: "Velvet Voltage",
    topProduct: false,
    likedProduct: false,
    quantity:0, 
    category: "Furniture",
    description: "Spacious 3-door wardrobe with stylish wallpapered design."
  },
  {
    id: 7,
    name: "Living Room Set",
    image: "https://assets.architecturaldigest.in/photos/67bc4651a4692f2dbc1cdf54/4:3/w_7152,h_5364,c_limit/Main%20Profile%20Image%20(1).jpg",
    price: 22000,
    oldPrice: 23999,
    inStock: true,
    brand: "Velvet Voltage",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Complete living room set including sofas, center table, and decor items."
  },
  {
    id: 8,
    name: "Bedroom Wallpaper",
    image: "https://www.shutterstock.com/image-illustration/modern-bedroom-design-green-wallpaper-600nw-2432697009.jpg",
    price: 8000,
    oldPrice: 8999,
    inStock: true,
    brand: "Rock Band Logos",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Premium green wallpaper to enhance the beauty of your bedroom."
  },
  {
    id: 9,
    name: "Office Chair",
    image: "https://media.wired.com/photos/61895f18da25312569a5af19/master/w_320,c_limit/Gear-Staples-Hyken-SOURCE-Staples.jpg",
    price: 7999,
    oldPrice: 10999,
    inStock: true,
    brand: "Catchy",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Ergonomic office chair with lumbar support and breathable mesh."
  },
  {
    id: 10,
    name: "Bookshelf",
    image: "https://previews.123rf.com/images/rukanoga/rukanoga1608/rukanoga160800051/64063208-3d-rendered-illustration-of-modern-empty-bookshelves.jpg",
    price: 4999,
    oldPrice: 6000,
    inStock: true,
    brand: "Hoobastank",
    topProduct: true,
    likedProduct: true,
    quantity:0,
    category: "Furniture",
    description: "Modern open bookshelf with multiple compartments for books and decor."
  },
  {
    id: 11,
    name: "TV Stand",
    image: "https://i.pinimg.com/736x/04/b1/02/04b102e6eca7f7e407586ef6d3c8364b.jpg",
    price: 6599,
    oldPrice: 8000,
    inStock: true,
    brand: "Elegant",
    topProduct: true,
    likedProduct: true,
    quantity:0,
    category: "Furniture",
    description: "Stylish wooden TV stand with shelves for console and storage."
  },
  {
    id: 12,
    name: "Recliner Sofa",
    image: "https://ushashriram.in/cdn/shop/products/91BFysI_w5L.jpg?v=1689025791",
    price: 19500,
    oldPrice: 21999,
    inStock: true,
    brand: "Franklin",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Comfortable recliner sofa for the ultimate lounging experience."
  },
  {
    id: 13,
    name: "Coffee Table",
    image: "https://shopps.in/wp-content/uploads/2022/04/c264b2b357c2428f9c80b7b1102586b9.webp",
    price: 4999,
    oldPrice: 5499,
    inStock: true,
    brand: "Italian",
    topProduct: true,
    likedProduct: true,
    quantity:0,
    category: "Furniture",
    description: "Sleek glass-top coffee table ideal for living rooms."
  },
  {
    id: 14,
    name: "King Size Bed",
    image: "https://damroimages.blob.core.windows.net/damroimages/9296-1.jpg",
    price: 24000,
    oldPrice: 25000,
    inStock: true,
    brand: "Duroflex",
    topProduct: true,
    likedProduct: true,
    quantity:0,
    category: "Furniture",
    description: "Sturdy king size bed frame with modern aesthetics."
  },
  {
    id: 15,
    name: "Wall Art Frame",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTHRaOHr59FWbm2BLNr2Khde1S3NKtcn6A9w&s",
    price: 3000,
    oldPrice: 3749,
    inStock: true,
    brand: "Mural",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Elegant wall art frame to elevate your room's ambiance."
  },
  {
    id: 16,
    name: "Dining Chair",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7P36uksF05Gr1OpIt5W-EB38DY8byn_aTGw&s",
    price: 8599,
    oldPrice: 10000,
    inStock: true,
    brand: " Urban Ladder",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Comfortable dining chair with a classic design, perfect for any dining room."
  },
  {
    id: 17,
    name: "Bar Stool",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ29oEq87pJO7Mh-k9mNRMwVv0sJx5sdoZsQ&s",
    price: 3999,
    oldPrice: 4500,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Stylish bar stool with a sturdy build, ideal for kitchen counters or bars."
  },
  {
    id: 18,
    name: "Accent Chair",
    image: "https://images.woodenstreet.de/image/cache/data/Ettorez/25-05/Daisy+Blue/Blue-750x650.jpg",
    price: 7999,
    oldPrice: 8969,
    inStock: true,
    brand: "Winchester Furniture",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Elegant accent chair with wingback design, perfect for reading nooks."
  },
  {
    id: 19,
    name: "Dressing Table",
    image: "https://cdn.shopify.com/s/files/1/0096/4594/9013/files/Dressing_Table_Design_Dressing_Table_New_Design_Wardrobe_With_Dressing_Table-3.jpg?v=1651385609",
    price: 16999,
    oldPrice: 18000,
    inStock: true,
    brand: "Elegant",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Modern dressing table with ample storage and a sleek finish."
  },
  {
    id: 20,
    name: "Console Table",
    image:"https://www.woodsala.com/cdn/shop/products/SGHWS0564_5.jpg?v=1613061371",
    price: 12999,
    oldPrice: 13999,
    inStock: true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Stylish console table perfect for entryways or living rooms, with a modern design."     
  },
  {
    id: 21,
    name: "Garden Bench",
    image: "https://www.familyhandyman.com/wp-content/uploads/2023/02/Timber-Outdoor-Garden-Bench-FHM.jpg?w=700",
    price: 7000,
    oldPrice: 7999,
    inStock: true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Sturdy garden bench made from weather-resistant materials, perfect for outdoor seating."
  },
  {
    id: 22,
    name: "Storage Ottoman",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKc8ZHAk9Y7N2Ax9K0M355OwT2xIpNg_1l8A&s",
    price: 2999,
    oldPrice: 3500,
    inStock: true,
    brand: "Pepperfry",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Versatile storage ottoman that doubles as a footrest or extra seating."
  },
  {
    id: 23,
    name: "Folding Table",
    image: "https://rathnastores.in/wp-content/uploads/2022/08/3-147.jpg",
    price: 3500,
    oldPrice: 5500,
    inStock: true,
    brand: "Nilkamal",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Compact folding table, ideal for small spaces or as a temporary dining solution."
  },
  {
    id: 24,
    name: "Pouffe",
    image:"https://torqueindia.co/cdn/shop/products/amalia-square-shape-fabric-ottoman-pouffe-puffy-566208.jpg?v=1685319373",
    price: 1500,
    oldPrice: 1700,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Soft pouffe that can be used as a footrest or extra seating, with a stylish design."
  },
  {   
     id: 25,
    name: "Shoe Rack",
    image: "https://www.bluewud.com/cdn/shop/files/SR-CLM-TM-_8_bb68e21c-1a1c-4551-baac-04a143c49eb9_700x700.jpg?v=1754908461",
    price: 3500,
    oldPrice: 4500,
    inStock: true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Functional shoe rack with multiple compartments, perfect for organizing footwear."
  },
  {
    id: 26,
    name: "Laundry Basket",
    image: "https://m.media-amazon.com/images/I/71g+mlY7M1L.jpg",
    price: 1200,
    oldPrice: 1100,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Stylish laundry basket with a lid, perfect for keeping your laundry organized."
  },
  {
    id: 27,
    name: "Wall Clock",
    image: "https://orpatgroup.com/wp-content/uploads/2022/08/DS-457-FRONT-GOLDEN-_MGL0379-09-12-21.jpg",
    price: 1200,
    oldPrice: 1700,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Minimalist wall clock with a sleek design, perfect for any room."
  },
  {
    id: 28,
    name: "Floor Lamp",
    image:"https://media-uk.landmarkshops.in/cdn-cgi/image/h=750,w=750,q=85,fit=cover/homecentre/1000012580496-1000012580495_01-2100.jpg",
    price: 2500,
    oldPrice: 2700,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Elegant floor lamp with adjustable height, ideal for reading corners."
   },
  {
    id: 29,
    name: "Table Lamp",
    image:"https://www.ikea.com/in/en/images/products/flyghoejd-table-lamp-brass-beige__1244487_pe921207_s5.jpg?f=xs",
    price: 1500,
    oldPrice: 1700,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Chic table lamp with a vintage design, perfect for bedside or study tables."
  },
  {
    id: 30,
    name: "Wall Shelf",
    image:"https://i.etsystatic.com/18961194/r/il/41421f/4797369905/il_570xN.4797369905_5sxq.jpg",
    price: 1000,
    oldPrice: 1200,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Simple wall shelf unit, perfect for displaying books or decor items."
},
  {
     id: 31,
     name: "Curtains",
     image:"https://ikiru.in/cdn/shop/products/buy-curtains-luxury-curtain-for-living-room-and-bedroom-cotton-beige-color-by-home4u-on-ikiru-online-store-1.jpg?v=1739201308",
      price: 2000,
      oldPrice: 2200,
      inStock: true,
      brand: "IKEA",
      topProduct: false,
      likedProduct: false,
      quantity:0,
      category: "Furniture",
      description: "Elegant white curtains that add a touch of sophistication to any room." 
    },
   {
     id: 32,
     name: "Crockery Unit",
     image:"https://rukminim2.flixcart.com/image/704/844/xif0q/kitchen-cabinet/e/h/l/400-0-rosewood-sheesham-three-drawer-angel-furniture-honey-original-imahybvurth2f5gu.jpeg?q=90&crop=false",
      price: 3000,
      oldPrice: 3500,
      inStock: true,
      brand: "Wooden Street",
      topProduct: false,
      likedProduct: false,
      quantity:0,
      category: "Furniture",
      description: "Natural woven rug that adds warmth and texture to your living space."
   },
   {
    id: 33,
    name: "Cushion Cover",
    image:"https://img.indiahandmade.com/catalog/product/cache/dee0bc41489afb86ae85561eae1bc64e/w/h/whatsapp_image_2023-06-11_at_1.45.08_pm.jpeg",
    price: 500,
    oldPrice: 349,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Soft cushion cover in a vibrant blue color, perfect for adding comfort to your sofa."
 },
  {
    id: 34,
    name: "Throw Blanket",
    image:"https://decure.in/cdn/shop/files/sf_classical_navy_melange.jpg?v=1716807374",
    price: 1200,
    oldPrice: 1000,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Cozy throw blanket made from soft fabric, perfect for snuggling up on chilly evenings."
  },
  {
    id: 35,
    name: "Wall Mirror",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2tfOv69FdNU-Cl1vb0MvnMbXtw9csxDilyg&s",
    price: 1800,
    oldPrice: 1600,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Stylish wall mirror with a wooden frame, perfect for adding depth to your room."
  },
  {
    id: 36,
    name: "Bedside Table",
    image:"https://magari.in/cdn/shop/files/Optimized_BedsideTable-DevonOption1_Angle.jpg?v=1745843086",
    price: 2500,
    oldPrice: 2700,
    inStock: true,
    brand: "Wooden Street",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Compact bedside table with a drawer, perfect for storing essentials next to your bed."
  },
  {
    id: 37,
    name: "Kitchen Cabinet",
    image:"https://www.oppeinhome.com/upload/images/ueditor/20230912/top-kitchen-design-ideas-that-inspire-you-1.webp",
    price: 5000,
    oldPrice: 5200,
    inStock: true,
    brand: "Wellborn Cabinet",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Spacious kitchen cabinet with multiple shelves, perfect for storing kitchen essentials."

  },
  {
    id: 38,
    name: "Bar Cart",
    image:"https://i.etsystatic.com/13280185/r/il/6536ed/2842625535/il_570xN.2842625535_32gv.jpg",
    price: 4000,
    oldPrice: 4200,
    inStock: true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Stylish bar cart with wheels, perfect for serving drinks or snacks at parties."
    },
  {
    id: 39,
    name: "Bunk Bed",
    image:"https://i.etsystatic.com/23425312/r/il/0e7316/3448109873/il_fullxfull.3448109873_t0ce.jpg",
    price: 21499,
    oldPrice: 23999,
    inStock: true,
    brand: "catchy",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Cozy pet bed designed for comfort, perfect for your furry friends."
  },
  {
    id: 40,
    name: "Outdoor Swing",
    image:"https://images.jdmagicbox.com/quickquotes/images_main/elegant-design-outdoor-swing-single-seater-2220008706-1cmh7k1j.jpg",
    price: 8000,
    oldPrice: 7500,
    inStock: true,
    brand: "Royal Ambience",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Relaxing outdoor swing made from durable materials, perfect for gardens or patios."
},
{
    id: 41,
    name: "Fire Pit",
    image: "https://images-cdn.ubuy.co.in/6825c0f975eec891040500fd-36-inch-fire-pit-with-grill-lid.jpg",
    price: 6000,
    oldPrice: 5500,
    inStock: true,
    brand: "FlameCraft",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Outdoor fire pit for cozy evenings, made from heat-resistant materials."
},
{
    id: 42,
    name: "Garden Shed",
    image: "https://5.imimg.com/data5/HG/PV/MY-9723342/wooden-garden-sheds-4m-x-2-5m.jpg",
    price: 12000,
    oldPrice: 13000,
    inStock: true,
    brand: "Palram",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Spacious garden shed for storing tools and equipment, made from weather-resistant materials."
},
{
    id: 43,
    name: "Outdoor Dining Set",
    image: "https://antiquehomedecors.com/wp-content/uploads/2025/01/images-3.jpg",
    price: 15000,
    oldPrice: 16000,
    inStock:true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Complete outdoor dining set with a table and chairs, perfect for alfresco dining."
},
{
    id: 44,
    name: "Heater",
    image: "https://longwayindia.com/cdn/shop/files/LW-Sunny-White-Sun-Heater-P1_1.jpg?v=1753255210&width=1024",
    price: 7000,
    oldPrice: 7500,
    inStock: true,
    brand: "LongWay",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Outdoor patio heater for keeping warm during chilly evenings, made from durable materials."
},
{
    id: 45,
    name: "Outdoor Storage Box",
    image: "https://hcluxuryoutdoor.com/cdn/shop/files/CharlestonStorageBoxFrontShot.jpg?v=1749059058",
    price: 3000,
    oldPrice: 3500,
    inStock: true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Weather-resistant outdoor storage box for keeping cushions and garden tools organized."
},
{
    id: 46,
    name: "Outdoor Lounge Chair",
    image: "https://cambridge-casual.com/cdn/shop/files/IT-121544T-TN_5_1500x.jpg?v=1737520990",
    price: 4000,
    oldPrice: 4200,
    inStock: true,
    brand: "Pepperfry",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Comfortable outdoor lounge chair with a modern design, perfect for relaxing in the sun."
},
{
    id: 47,
    name: "Outdoor Coffee Table",
    image: "https://www.royaloakindia.com/media/catalog/product/r/o/royaloak-aura-banana-coffee-table-in-teak-wood-3.jpg?width=800&height=500&canvas=800,500&optimize=high&bg-color=255,255,255&fit=bounds",
    price: 2500,
    oldPrice: 2700,
    inStock: true,
    brand: "Wooden Street",
    topProduct: false,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Stylish outdoor coffee table made from weather-resistant materials, perfect for patios."
},
{
   id : 48,
   name: "Single Size Bed",
   image: "https://images.durian.in/Durian/durian/product/800x800/794781730790163.jpg",
    price: 7000,
    oldPrice: 7500,
    inStock: true,
    brand: "Wooden Street",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Compact single size bed with a modern design, perfect for small bedrooms."
},
{
    id: 49,
    name: "File Cabinet",
    image: "https://res.cloudinary.com/hni-corporation/image/upload/d_HON:Brand:Icons:HON_Icon_Outlines_HON-Icon-Gallery-001.png/f_auto,q_auto/v1584035521/HON/Filing%20and%20Storage/310%20Series/HON-310Series-H312-500-001.jpg",
    price: 4000,
    oldPrice: 4200,
    inStock: true,
    brand: "IKEA",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Sturdy file cabinet with multiple drawers, perfect for organizing office documents."
},
{
    id: 50,
    name: "Conference Table",
    image: "https://vavafurniture.com/wp-content/uploads/2023/03/MA-MNC8TBS-2.jpg",
    price: 22000,
    oldPrice: 23999,
    inStock: true,
    brand: "Herman Miller",
    topProduct: true,
    likedProduct: false,
    quantity:0,
    category: "Furniture",
    description: "Spacious outdoor daybed with cushions, perfect for lounging in the garden."
},
{
     id:51,
     name:"study table",
     image:"https://ik.imagekit.io/2xkwa8s1i/img/npl_modified_images/Apollo_new/WSTAPOLLOCWR1_1.jpg?tr=w-1200",
     price: 5000,
     oldPrice: 5200,
     inStock: true,
     brand: "Wooden Street",
     topProduct: false,
     likedProduct: false,
     quantity:0,
     category: "Furniture",
     description: "Modern study table with ample workspace and storage, perfect for home offices."
},
{
  id: 52,
  name: "Rounded Table",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgkWsmKXb6TjCJsE_-_wCSDFz3_XiWgsCeTg&s",
  price: 4999,
  oldPrice: 5399,
  inStock: true,
  brand: "Wooden Street",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Stylish rounded table with a modern design, perfect for dining or coffee areas."
},
{
  id: 53,
  name: "Ladder",
  image: "https://m.media-amazon.com/images/I/51WUsxa7wpL._UF894,1000_QL80_.jpg",
  price: 3499,
  oldPrice: 3899,
  inStock: true,
  brand: "Home Decor",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Sturdy wooden ladder for home use, perfect for reaching high shelves or storage."
},
 { 
  id: 54, 
  name: "Hammock", 
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ84QYad8O8pPZ9CXcHvhL0mq0kxmu7qhGA5nH0thTLviKLtPh59GMUaeU_C-oI1hKbIMY&usqp=CAU",
  price: 2000, 
  oldPrice: 2200,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Relaxing hammock made from durable fabric, perfect for outdoor lounging."
 },
 {
  id :55,
  name:"Computer Desk",
  image: "https://www.ikea.com/in/en/images/products/micke-desk-white__1162647_pe889914_s5.jpg",
  price:7990 ,
  oldPrice: 8999,
  inStock: true,
  brand: "Micke",
  topProduct: false,
  likedProduct: true,
  quantity: 0,
  category: "Furniture",
  description: "Modern computer desk with a sleek design, perfect for home offices or study areas."
 },
 {
  id: 56,
  name: "Bean Bag",
  image: "https://cdn.grofers.com/app/images/products/sliding_image/369877a.jpg?ts=1721647310",
  price: 1500,
  oldPrice: 1800,
  inStock: true,
  brand: "Urban Ladder",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Comfortable bean bag chair, perfect for casual seating in living rooms or bedrooms."
 },
 {
  id: 58,
  name:"chest of drawers",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrKw1nEt1HSsJ9OjeUOJ4OFn-lNLrVJ2Z6cVLm7BBaPPjrFXdGmDDnminRdfUQ5Gpj1xM&usqp=CAU",
  price: 11999,
  oldPrice: 14999,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Spacious chest of drawers with a modern design, perfect for bedroom storage."
 },
 {
  id:59,
  name:"Kid Chair",
  image: "https://vivo-us.com/cdn/shop/files/DESK-V201P-CH_01.jpg?v=1762525646&width=1928",
  price: 1399,
  oldPrice: 1500,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Colorful and comfortable chair designed for kids, perfect for playrooms or study areas."
 },
 {
  id:60,
  name:"Toy Storage",
  image: "https://miniture.in/cdn/shop/files/modo-space-contour-kids-storage-cabinet-2-tray-1-with-pushcart-594.webp?v=1753189809",
  price: 1499,
  oldPrice: 2000,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Spacious toy storage unit with multiple compartments, perfect for organizing children's toys.",
 },
 {
   id:61,
   name:"Corner Stand",
   image: "https://indowood.in/wp-content/uploads/2024/11/Magazine-Stand-522-1.jpg",
   price: 4999,
   oldPrice: 6000,
   inStock: true,
   brand: "IKEA",
   topProduct: false,
   likedProduct: false,
   quantity: 0,
   category: "Furniture",
   description: "Stylish corner stand with multiple shelves, perfect for displaying decor items or books."
 },
 {
  id:62,
  name:"Nesting Tables",
  image: "https://www.nismaayadecor.in/cdn/shop/files/nismaaya-gavin-nesting-tables-set-of-3_3.png?v=1686820010&width=1080",
  price: 6499,
  oldPrice: 7500,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Set of nesting tables with a modern design, perfect for small spaces or as side tables."
 },
 {
  id:63,
  name:"Mattress",
  image: "https://www.ikea.com/in/en/images/products/vesteroey-pocket-sprung-mattress-extra-firm-light-blue__1150853_pe884906_s5.jpg",
  price: 7999,
  oldPrice: 8500,
  inStock: true,
  brand: "Sleepwell",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Comfortable mattress with memory foam, perfect for a good night's sleep."
 },
 {
  id:64,
  name:"Headboard",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-pD3tx0pOweX0XKjb_1h0wkgczdDXofd-ag&s",
  price: 6999,
  oldPrice: 7500,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Elegant headboard with a classic design, perfect for enhancing your bedroom decor."
 },
 {
  id:65,
  name:"Sofa Bed",
  image: "https://5.imimg.com/data5/SELLER/Default/2023/4/298852771/HP/QA/DA/145919979/high-quality-sofa-cum-bed.jpg",
  price: 14999,
  oldPrice: 17999,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Versatile sofa bed that easily converts into a comfortable sleeping space."
 },
 {
  id:66,
  name:"Small wardrobe",
  image: "https://m.media-amazon.com/images/I/51RxSZU4ZWL._UF894,1000_QL80_.jpg",
  price: 11999,
  oldPrice: 14999,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Compact wardrobe with ample storage space, perfect for small bedrooms."
 },
 {
  id:67,
  name:"Garden chair",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQh4Fi6dWImGGiXklbaMD3lrbg4NXoxGJjvVhIexCCAEWfQ5POAHoloN2yeSKeoHfN3PW4&usqp=CAU",
  price: 6999,
  oldPrice: 7499,
  inStock: true,
  brand: "IKEA",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Stylish garden chair and table set, perfect for outdoor dining or relaxation."
 },
 {
  id:68,
  name:"Room Divider",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJB2R3RH874309WvzC9rn0DI_F2Mrm-PANUA&s",
  price: 4799,
  oldPrice: 5499,
  inStock: true,
  brand: "Wooden Asian",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Elegant room divider/partition that adds privacy and style to your living space."
 },
 {
  id:69,
  name:"Dining Bench",
  image: "https://i0.wp.com/handicraftpoint.com/wp-content/uploads/2023/10/HP110279-1.jpg",
  price: 4999,
  oldPrice: 5999,
  inStock: true,
  brand: "American Signature",
  topProduct: false,
  likedProduct: false,
  quantity: 0,
  category: "Furniture",
  description: "Stylish dining bench with a modern design, perfect for adding extra seating to your dining area.",
 },
 {
   id:70,
   name:"Queen Size Bed",
   image: "https://images.woodenstreet.de/image/cache/data/bed-with-storage/brixton-sheesham-wood-bed-with-storage-drawers-king-size-honey-finish/new-logo/New+Looks+/3-810x702.jpg",
    price: 15999,
    oldPrice: 17999,
    inStock: true,
    brand: "IKEA",
    topProduct: false,
    likedProduct: false,
    quantity: 0,
    category: "Furniture",
    description: "Spacious queen size bed with a modern design, perfect for master bedrooms.",
   },
// ======================================
// ADD THIS INSIDE YOUR productData ARRAY
// ======================================

// BED PRODUCTS
{
  id: 71,
  name: "Luxury King Size Bed",
  image:
    "https://damroimages.blob.core.windows.net/damroimages/9296-1.jpg",
  price: 28999,
  oldPrice: 32999,
  inStock: true,
  brand: "Sleepwell",
  topProduct: true,
  likedProduct: false,
  quantity: 0,
  category: "Bed",
  type: "bed",

  availableSizes: [
    {
      name: "Single",
      dimensions: '36" × 75"',
      room: "Small Room",
      suitable: "1 Person",
      price: 18999,
    },

    {
      name: "Queen",
      dimensions: '60" × 78"',
      room: "Medium Room",
      suitable: "Couples",
      price: 24999,
    },

    {
      name: "King",
      dimensions: '72" × 78"',
      room: "Master Bedroom",
      suitable: "Family Comfort",
      price: 28999,
    },
  ],

  description:
    "Premium luxury king size bed with modern finish and storage design.",
},

{
  id: 72,
  name: "Modern Queen Bed",
  image:
    "https://images.woodenstreet.de/image/cache/data/bed-with-storage/brixton-sheesham-wood-bed-with-storage-drawers-king-size-honey-finish/new-logo/New+Looks+/3-810x702.jpg",
  price: 21999,
  oldPrice: 24999,
  inStock: true,
  brand: "Wooden Street",
  topProduct: true,
  likedProduct: false,
  quantity: 0,
  category: "Bed",
  type: "bed",

  availableSizes: [
    {
      name: "Single",
      dimensions: '36" × 75"',
      room: "Compact Room",
      suitable: "Single Person",
      price: 15999,
    },

    {
      name: "Queen",
      dimensions: '60" × 78"',
      room: "2BHK Bedroom",
      suitable: "Couples",
      price: 21999,
    },

    {
      name: "King",
      dimensions: '72" × 78"',
      room: "Large Bedroom",
      suitable: "Luxury Comfort",
      price: 26999,
    },
  ],

  description:
    "Elegant queen size bed with premium wood finish and stylish headboard.",
},

// SOFA PRODUCTS
{
  id: 73,
  name: "Velvet Premium Sofa",
  image:
    "https://alder.in/wp-content/uploads/2024/05/Waves-311.jpg",
  price: 18999,
  oldPrice: 22999,
  inStock: true,
  brand: "Velvet",
  topProduct: true,
  likedProduct: true,
  quantity: 0,
  category: "Sofa",
  type: "sofa",

  availableSizes: [
    {
      name: "2 Seater",
      dimensions: '63" × 38" × 34"',
      suitable: "Small Family",
      price: 14999,
    },

    {
      name: "3 Seater",
      dimensions: '90" × 38" × 34"',
      suitable: "Family Use",
      price: 18999,
    },

    {
      name: "4 Seater",
      dimensions: '117" × 38" × 34"',
      suitable: "Large Family",
      price: 23999,
    },

    {
      name: "5 Seater",
      dimensions: '144" × 38" × 34"',
      suitable: "Luxury Hall",
      price: 27999,
    },

    {
      name: "6 Seater",
      dimensions: '171" × 38" × 34"',
      suitable: "Big Living Room",
      price: 31999,
    },

    {
      name: "7 Seater",
      dimensions: '198" × 38" × 34"',
      suitable: "Premium Villa",
      price: 35999,
    },
  ],

  description:
    "Modern velvet sofa with premium comfort and luxurious finishing.",
},

{
  id: 74,
  name: "Luxury Recliner Sofa",
  image:
    "https://ushashriram.in/cdn/shop/products/91BFysI_w5L.jpg?v=1689025791",
  price: 24999,
  oldPrice: 28999,
  inStock: true,
  brand: "Franklin",
  topProduct: true,
  likedProduct: false,
  quantity: 0,
  category: "Sofa",
  type: "sofa",

  availableSizes: [
    {
      name: "2 Seater",
      dimensions: '63" × 38" × 34"',
      suitable: "Compact Living Room",
      price: 19999,
    },

    {
      name: "3 Seater",
      dimensions: '90" × 38" × 34"',
      suitable: "Family Lounge",
      price: 24999,
    },

    {
      name: "4 Seater",
      dimensions: '117" × 38" × 34"',
      suitable: "Luxury Hall",
      price: 29999,
    },

    {
      name: "5 Seater",
      dimensions: '144" × 38" × 34"',
      suitable: "Big Family",
      price: 33999,
    },

    {
      name: "6 Seater",
      dimensions: '171" × 38" × 34"',
      suitable: "Premium Home",
      price: 37999,
    },

    {
      name: "7 Seater",
      dimensions: '198" × 38" × 34"',
      suitable: "Villa Interior",
      price: 41999,
    },
  ],

  description:
    "Luxury recliner sofa with soft cushioning and premium comfort seating.",
},
];

export default productData;
